### ISSUE TITLE
Pathes with 2 or more slashes not works

### ISSUE THREAD

**Issue by DanielHreben** [dsummersl/node-xml2js-xpath#1]
There are no matching regexp in `find()` for long pathes containing 2 or more '/' symbols, eg.
`/TransactionResponse/FundingResult/Date`

**Comment by dsummersl** [comment]
ah...k. I'll write up a test case and get this fixed today. Thanks for the report.

**Comment by dsummersl** [comment]
Added a fix - let me know if you see any issues. Thanks!

**Comment by DanielHreben** [comment]
Please bump version of package and push update to the npm.

**Comment by dsummersl** [comment]
doh. published.

**Comment by DanielHreben** [comment]
Version number was not changed, so npm still installs buggy version on my machine

**Comment by dsummersl** [comment]
hmm, looks right to me. upgrade your package.json to 0.5.0? I see its updated on npm: https://www.npmjs.com/package/xml2js-xpath

**Comment by DanielHreben** [comment]
Sorry, my fault.
