### ISSUE TITLE
XPath select based on child value(s)

### ISSUE THREAD

**Issue by jrama-arcanys** [dsummersl/node-xml2js-xpath#16]
Is there support for this feature?
For example:
```
<books>
    <book>
        <author>Tom</author>
        <genre>Science</genre>
    </book>
    <book>
        <author>Mike</author>
        <genre>Politics</genre>
    </book>
</books>
```
var matches = xpath.find(json, "/books/book[genre='Science']/author");
> returns [ ] but should return "Tom"

**Comment by i3fox** [comment]
I have same problem.

```
<meters>
    <meter>
        <type>1</type>
        <model>2</model>
    </meter>
    <meter>
        <type>2</type>
        <model>5</model>
    </meter>
</meters>
```
```
const matches = xpath.find(json, "/meters/meter[type='1']");

return []
```

**Comment by dsummersl** [comment]
Hi all, thanks for reporting this - I did start looking into this last week. I'll try and get a fix out soon. Thanks for the examples - they help writing up the test cases and verifying the feature.

**Comment by dsummersl** [comment]
v0.11.0 has been published with this feature.

**Comment by dsummersl** [comment]
(thanks to @jun2xrama!)
