### ISSUE TITLE
How much of the xpath spec is implemented?

### ISSUE THREAD

**Issue by martinheidegger** [dsummersl/node-xml2js-xpath#3]
I tried to port xpath from libxmljs-dom to node-xml2js-xpath. Unfortunately several features of xpath seem to be not implemented.
1. Node names are node case insensitive: `.find('//DIV')` instead of `.find('//div')` is required for  `<DIV>`
2. Properties don't seem to work `.find('//DIV[@class="..."]')`
3. It doesn't find all elements when looking deep `.find('//DIV')` of `<html><div><div></div><div></div><div></div></div></html>` should find 4 divs not 2.

So I wondered: how many cases are implemented?

**Comment by dsummersl** [comment]
Hi @martinheidegger sorry for the late response, I only now noticed this. See the test cases for examples (https://github.com/dsummersl/node-xml2js-xpath/blob/master/test/xpath.js#L71).

I know its been a while, but if you have a sample doc that causes the problems you describe I'd be happy to test/fix whatever issues you encounter.
