### ISSUE TITLE
Support for Namespace?

### ISSUE THREAD

**Issue by danosaure** [dsummersl/node-xml2js-xpath#5]
Do you have any example for supporting namespaces?

**Comment by dsummersl** [comment]
I don't think so, but I can add one. Do you have a sample of the kind of namespaced document you would like to work with?

**Comment by danosaure** [comment]
Let me get back to you with a PR with a test suite TDD style, probably next week.

**Comment by dsummersl** [comment]
Thanks @danosaure, if you have any questions feel free to ping me.
